sudo: required
services: docker
language: c
compiler:
  - clang
  - gcc
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcups2-dev
script: ./autogen.sh && ./configure && make
