name: Deploy Workflow
on:
  push:
    tags:
      - "*"

jobs:
  build-linux:
    name: Build Linux
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: python:3.14

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install system dependencies
        run: apt-get update && apt-get install -y libcups2-dev

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: pip install setuptools pytest build

      - name: Install package
        run: pip install .

      - name: Run tests
        run: pytest

      - name: Build source distribution
        run: python -m build --sdist

      - name: Upload source distribution
        uses: actions/upload-artifact@v7
        with:
          name: sdist
          path: dist/*.tar.gz

  build-windows:
    name: Build Windows
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          3.6,
          3.7,
          3.8,
          3.9,
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3.14"
        ]
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: pip install setuptools pytest build

      - name: Install package
        run: pip install .

      - name: Run tests
        run: pytest

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v7
        with:
          name: wheel-${{ matrix.python-version }}
          path: dist/*.whl

  build-windows-arm:
    name: Build Windows ARM
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          "3.11",
          "3.12",
          "3.13",
          "3.14"
        ]
    runs-on: windows-11-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: arm64

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: pip install setuptools pytest build

      - name: Install package
        run: pip install .

      - name: Run tests
        run: pytest

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v7
        with:
          name: wheel-arm-${{ matrix.python-version }}
          path: dist/*.whl

  deploy:
    name: Publish to PyPI
    needs: [build-linux, build-windows, build-windows-arm]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: python:3.14

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true

      - name: Install dependencies
        run: pip install twine

      - name: Check version of distributions
        run: ls "dist/npcolony-${GITHUB_REF_NAME}.tar.gz"

      - name: Upload to PyPI
        run: python -m twine upload --skip-existing --non-interactive dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
